### ISSUE TITLE
Module Admin. Menu MDB - Changes of MDBs can not be saved

### ISSUE THREAD

**Issue by rompik** [eryar/PipeCAD#9]
After adding any user into Teams or db into MDB ans press OK button system doesn't save changes into database. Looks like method PipeCad.SaveWork() is not completed for Team/MDB changes.

**Comment by eryar** [comment]
These function are developed by Python, I will fix this and share the Python file.
Thanks.

**Comment by eryar** [comment]
I have fixed this and upload python plugins, you can download them and copy to PipeCAD/plugins/PipeCAD folder to have a try.

**Comment by rompik** [comment]
Unfortunatelly after updating Python files problem is not fixed. it could be there will need also update PipeCAD.exe file. Current version of it is 1.0.0.0 from 01.01.2022 10:48. I attached short video to explain issue with updating MDB - 
https://user-images.githubusercontent.com/12736532/160154648-6674f2ed-b438-4d94-9181-22116faa8ee5.mp4

.

**Comment by eryar** [comment]
Fixed PipeCAD1.0.1
